# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurement', '0023_auto_20170124_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week', models.PositiveIntegerField()),
                ('day_download', models.FloatField()),
                ('day_upload', models.FloatField()),
                ('day_ping', models.IntegerField()),
                ('day_max_ping', models.IntegerField()),
                ('day_min_ping', models.IntegerField()),
                ('week_download', models.FloatField()),
                ('week_upload', models.FloatField()),
                ('week_ping', models.IntegerField()),
                ('week_max_ping', models.IntegerField()),
                ('week_min_ping', models.IntegerField()),
                ('month_download', models.FloatField()),
                ('month_upload', models.FloatField()),
                ('month_ping', models.IntegerField()),
                ('month_max_ping', models.IntegerField()),
                ('month_min_ping', models.IntegerField()),
                ('year_download', models.FloatField()),
                ('year_upload', models.FloatField()),
                ('year_ping', models.IntegerField()),
                ('year_max_ping', models.IntegerField()),
                ('year_min_ping', models.IntegerField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Metric')),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Probe')),
            ],
        ),
    ]
