# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_flag_uuid'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytest',
            name='flag',
        ),
        migrations.AddField(
            model_name='ndtmeasurement',
            name='flag',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ndts', to='measurement.Flag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ndtmeasurement',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndts', to='measurement.Metric'),
        ),
    ]
