# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcp',
            name='target',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
