# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170522_1946'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dns',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Target'),
        ),
        migrations.AddField(
            model_name='http',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Target'),
        ),
        migrations.AddField(
            model_name='tcp',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Target'),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ISP'),
        ),
        migrations.AlterField(
            model_name='ndt',
            name='isp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.ISP'),
        ),
    ]
