# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 22:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20170328_2239'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndt_measurement_count', models.PositiveIntegerField(default=0)),
                ('av_upload_speed', models.FloatField()),
                ('av_download_speed', models.FloatField()),
                ('av_ping', models.FloatField()),
                ('av_max_ping', models.FloatField()),
                ('av_min_ping', models.FloatField()),
                ('av_timeout', models.FloatField()),
                ('av_package_loss', models.FloatField()),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Flag')),
                ('isp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.ISP')),
            ],
        ),
        migrations.CreateModel(
            name='NDTMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('upload_speed', models.FloatField()),
                ('download_speed', models.FloatField()),
                ('ping', models.FloatField()),
                ('max_ping', models.FloatField()),
                ('min_ping', models.FloatField()),
                ('timeout', models.FloatField()),
                ('package_loss', models.FloatField()),
                ('daily_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ndt', to='plugins.DailyTest')),
                ('isp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.ISP')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndt', to='measurement.Metric')),
            ],
        ),
        migrations.RemoveField(
            model_name='daytest',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='daytest',
            name='probe',
        ),
        migrations.AddField(
            model_name='http',
            name='body_proportion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dns',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dns',
            name='control_resolver_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dns',
            name='flag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dnss', to='measurement.Flag'),
        ),
        migrations.AlterField(
            model_name='dns',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dnss', to='measurement.Metric'),
        ),
        migrations.AlterField(
            model_name='http',
            name='flag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='https', to='measurement.Flag'),
        ),
        migrations.AlterField(
            model_name='http',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='https', to='measurement.Metric'),
        ),
        migrations.AlterField(
            model_name='tcp',
            name='flag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcps', to='measurement.Flag'),
        ),
        migrations.AlterField(
            model_name='tcp',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcps', to='measurement.Metric'),
        ),
        migrations.AlterField(
            model_name='tcp',
            name='status_failure',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='DayTest',
        ),
    ]
