# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns',
            name='flag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.Flag'),
        ),
        migrations.AlterField(
            model_name='dns',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.Metric'),
        ),
    ]
