# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20170404_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NDTMeasurement',
            new_name='NDT',
        ),
    ]
