# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_flag_uuid'),
        ('plugins', '0002_auto_20170328_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytest',
            name='flag',
        ),
        migrations.AddField(
            model_name='ndtmeasurement',
            name='flag',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ndts', to='measurement.Flag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='av_download_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='av_max_ping',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='av_min_ping',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='av_package_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='av_ping',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='av_timeout',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='av_upload_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ndtmeasurement',
            name='daily_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='plugins.DailyTest'),
        ),
        migrations.AlterField(
            model_name='ndtmeasurement',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndts', to='measurement.Metric'),
        ),
    ]
