# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_tcp_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytest',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ISP'),
        ),
        migrations.AlterField(
            model_name='ndt',
            name='isp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.ISP'),
        ),
    ]
