# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20170522_1605'),
        ('plugins', '0003_auto_20170425_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='dns',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Target'),
        ),
        migrations.AddField(
            model_name='http',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Target'),
        ),
        migrations.AlterField(
            model_name='tcp',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Target'),
        ),
    ]
