# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_auto_20170314_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='http',
            name='flag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='https', to='measurement.Flag'),
        ),
        migrations.AlterField(
            model_name='http',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='https', to='measurement.Metric'),
        ),
    ]
