# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 18:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_http_body_proportion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dns',
            name='control_resolver_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
