# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_auto_20170317_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcp',
            name='flag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcps', to='measurement.Flag'),
        ),
        migrations.AlterField(
            model_name='tcp',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcps', to='measurement.Metric'),
        ),
        migrations.AlterField(
            model_name='tcp',
            name='status_failure',
            field=models.TextField(null=True),
        ),
    ]
