# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_auto_20170328_1738'),
        ('plugins', '0008_auto_20170320_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndt_measurement_count', models.PositiveIntegerField()),
                ('av_upload_speed', models.FloatField()),
                ('av_download_speed', models.FloatField()),
                ('av_ping', models.FloatField()),
                ('av_max_ping', models.FloatField()),
                ('av_min_ping', models.FloatField()),
                ('av_timeout', models.FloatField()),
                ('av_package_loss', models.FloatField()),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Flag')),
                ('isp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.ISP')),
            ],
        ),
        migrations.CreateModel(
            name='NDTMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_speed', models.FloatField()),
                ('download_speed', models.FloatField()),
                ('ping', models.FloatField()),
                ('max_ping', models.FloatField()),
                ('min_ping', models.FloatField()),
                ('timeout', models.FloatField()),
                ('package_loss', models.FloatField()),
                ('daily_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.DailyTest')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Metric')),
            ],
        ),
        migrations.RemoveField(
            model_name='daytest',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='daytest',
            name='probe',
        ),
        migrations.DeleteModel(
            name='DayTest',
        ),
    ]
