# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
