# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170412_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_flags',
            field=models.CharField(blank=True, choices=[('dns', 'dns'), ('http', 'http'), ('ndt', 'ndt'), ('none', 'none'), ('tcp', 'tcp')], default='none', max_length=10, null=True),
        ),
    ]
