# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('bloqueo por DPI', 'bloqueo por DPI'), ('bloqueo por DNS', 'bloqueo por DNS'), ('bloqueo por IP', 'bloqueo por IP'), ('Interceptacion de trafico', 'Interceptaci\xf3n de tr\xe1fico'), ('falla de dns', 'falla de dns'), ('Velocidad de internet', 'Velocidad de internet'), ('alteracion de trafico por intermediarios', 'alteraci\xf3n de tr\xe1fico por intermediarios')], default='null', max_length=100),
            preserve_default=False,
        ),
    ]
