# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_type_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plugin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
