# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170711_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='event.Site'),
        ),
    ]
