# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_plugin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type_flags',
        ),
    ]
