# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20161129_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
