# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20161129_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='name',
        ),
        migrations.AddField(
            model_name='url',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Site'),
        ),
    ]
