# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20161129_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='identification',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
