# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('domain', 'Domain'), ('url', 'Url'), ('ip', 'Ip')], default='domain', max_length=10),
        ),
    ]
