# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_event_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('bloqueo', 'Bloqueo'), ('desconexion', 'Desconexion'), ('relentizacion', 'Relentizacion de servicio en Linea'), ('conexion', 'Conexion inusualmente lenta'), ('interceptacion', 'Interceptacion de trafico'), ('falla', 'Falla Importante'), ('dos', 'DoS')], max_length=20)),
                ('draft', models.BooleanField(default=True)),
                ('events', models.ManyToManyField(related_name='cases', to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('info', 'Info'), ('grave', 'Grave'), ('positivo', 'Positivo')], max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Case.Case')),
            ],
        ),
    ]
