# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Case.Case'),
        ),
    ]
