# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 12:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Case', '0002_auto_20161125_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='update',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
