# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0003_auto_20161128_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
