# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0005_auto_20161207_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(),
        ),
    ]
