# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0008_auto_20161221_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
    ]
