# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0010_auto_20170110_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
