# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0011_auto_20170110_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category_de',
        ),
        migrations.RemoveField(
            model_name='case',
            name='category_es',
        ),
    ]
