# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0010_case_twitter_search'),
        ('Case', '0012_auto_20170110_1742'),
    ]

    operations = [
    ]
