from django import forms
from django.forms.models import inlineformset_factory
from django.forms import DateTimeField
from Case.models import Case, Update, Category


class CaseForm(forms.ModelForm):
    open_ended = forms.BooleanField(widget=forms.CheckboxInput(),
                                    required=False)
    events = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'hidden'}), required=False, label="")

    start_date = DateTimeField(
        widget=forms.widgets.DateTimeInput(
            format='%m/%d/%Y'))

    end_date = DateTimeField(
        widget=forms.widgets.DateTimeInput(
            format='%m/%d/%Y'),
        required=False)

    #   title_de: case title in english.
    #   This field was auto-generated by django-modeltranslate
    title_de = forms.CharField(
        widget=forms.TextInput(), label="Title [English] (optional)",
        required=False)

    #   description_de: case description in english.
    #   This field was auto-generated by django-modeltranslate
    description_de = forms.CharField(
        widget=forms.Textarea(), label="Description [English] (optional)",
        required=False)

    class Meta:
        model = Case
        fields = [
            'title', 'description', 'start_date', 'end_date',
            'category', 'open_ended', 'draft', 'events',
            'title_de', 'description_de'
        ]


class CategoryForm(forms.ModelForm):

    #   display_name_de: category display name in english.
    #   This field was auto-generated by django-modeltranslate
    display_name_de = forms.CharField(
        widget=forms.TextInput(), label="Display Name [English] (optional)",
        required=False)

    class Meta:
        model = Category
        fields = [
            'name', 'display_name', 'display_name_de'
        ]


class UpdateForm(forms.ModelForm):
    # date = forms.DateField(widget=forms.TextInput(
    #     attrs={'class': 'update_date'}),
    #     required=True)
    date = DateTimeField(
        widget=forms.widgets.DateTimeInput(
            format='%m/%d/%Y',
            attrs={'class': 'update_date'}))

    #   title_de: update title in english. This field was auto-generated
    #   by django-modeltranslate
    title_de = forms.CharField(
        widget=forms.TextInput(), label="Title [English] (optional)",
        required=False)

    #   text_de: update title in english. This field was auto-generated
    #   by django-modeltranslate
    text_de = forms.CharField(
        widget=forms.Textarea(), label="Text [English] (optional)",
        required=False)

    class Meta:
        model = Update
        fields = [
            'title', 'text', 'category', 'date',
            'title_de', 'text_de'
        ]


UpdateFormSet = inlineformset_factory(
    Case,
    Update,
    form=UpdateForm,
    extra=0,
    can_delete=True
)
