from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'^create/$',
        views.CreateCase.as_view(),
        name='create-case'
    ),
    url(
        r'^$',
        views.ListCase.as_view(),
        name='list-case'
    ),
    url(
        r'^(?P<pk>[0-9]+)/detail/$',
        views.DetailCase.as_view(),
        name='detail-case'
    ),
    url(
        r'^(?P<pk>[0-9]+)/change-status/$',
        views.ChangeCaseStatus.as_view(),
        name='change-case-status'
    ),
    url(
        r'^(?P<pk>[0-9]+)/change-status-detail/$',
        views.ChangeCaseStatusDetail.as_view(),
        name='change-case-status-detail'
    ),
    url(
        r'^(?P<pk>[0-9]+)/delete/$',
        views.DeleteCase.as_view(),
        name='delete-case'
    ),
    url(
        r'^(?P<pk>[0-9]+)/update/$',
        views.UpdateCase.as_view(),
        name='update-case'
    ),
    url(
        r'^(?P<pk>[0-9]+)/create-update/$',
        views.CreateUpdate.as_view(),
        name='create-update'
    ),
    url(
        r'^(?P<pk>[0-9]+)/edit-update/$',
        views.UpdateUpdate.as_view(),
        name='update-update'
    ),
    url(
        r'^(?P<pk>[0-9]+)/delete-update/$',
        views.DeleteUpdate.as_view(),
        name='delete-update'
    ),
    url(
        r'^create_from_events/$',
        views.CreateCaseFromEventsView.as_view(),
        name='create-case-from-events'
    ),
    url(
        r'^category/$',
        views.ListCategory.as_view(),
        name='list-category'
    ),
    url(
        r'^category/create/$',
        views.CreateCategory.as_view(),
        name='create-category'
    ),
    url(
        r'^category/(?P<pk>[0-9]+)/delete/$',
        views.DeleteCategory.as_view(),
        name='delete-category'
    ),
    url(
        r'^category/(?P<pk>[0-9]+)/update/$',
        views.UpdateCategory.as_view(),
        name='update-category'
    ),
]
