# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp', models.CharField(max_length=50, verbose_name='Operadora')),
                ('verbose', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicion', models.CharField(max_length=40, verbose_name='Id de la Medicion')),
                ('ip', models.GenericIPAddressField()),
                ('flag', models.NullBooleanField(default=False)),
                ('type_med', models.CharField(choices=[('MED', 'Medicion'), ('DNS', 'Medicion DNS'), ('TCP', 'Medicion TCP'), ('HTTP', 'Medicion HTTP')], default='MED', max_length=50, verbose_name='Tipo de Medicion')),
            ],
        ),
    ]
