# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AlterField(
            model_name='probe',
            name='country',
            field=models.ForeignKey(default=231, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.Country'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='region',
            field=models.ForeignKey(default=3479, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.State'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
