# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170522_1946'),
        ('plugins', '0002_auto_20170522_1946'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutedInput',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='isp',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AddField(
            model_name='flag',
            name='plugin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Target'),
        ),
        migrations.AlterField(
            model_name='dns',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ISP', verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='suggested_events',
            field=models.ManyToManyField(blank=True, related_name='suggested_flags', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='country',
            field=models.ForeignKey(default=231, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.Country'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ISP'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.Plan'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='region',
            field=models.ForeignKey(default=3479, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.State'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='ISP',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
