# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicion', models.CharField(max_length=40, verbose_name='Id de la Medicion')),
                ('flag', models.NullBooleanField(default=False)),
            ],
        ),
    ]
