# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='input',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='report_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
