# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=50)),
                ('annotations', models.TextField()),
                ('report_id', models.CharField(max_length=100)),
                ('report_filename', models.CharField(max_length=150)),
                ('options', models.TextField()),
                ('probe_cc', models.CharField(max_length=50)),
                ('probe_asn', models.CharField(max_length=50)),
                ('probe_ip', models.GenericIPAddressField()),
                ('data_format_version', models.CharField(max_length=10)),
                ('test_name', models.CharField(max_length=25)),
                ('test_start_time', models.DateTimeField()),
                ('measurement_start_time', models.DateTimeField()),
                ('test_runtime', models.FloatField()),
                ('test_helpers', models.TextField()),
                ('test_keys', models.TextField()),
                ('software_name', models.CharField(max_length=15)),
                ('software_version', models.CharField(max_length=10)),
                ('test_version', models.CharField(max_length=10)),
                ('bucket_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
        migrations.AddField(
            model_name='flag',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
