# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dns',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.ISP', verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag',
            field=models.CharField(choices=[('hard', 'Hard'), ('muted', 'Muted'), ('none', 'None'), ('soft', 'Soft')], db_index=True, default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='flag',
            name='manual_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='metric',
            name='input',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='measurement_start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='report_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='metric',
            name='test_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='metric',
            name='test_version',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.ISP'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.ISP'),
        ),
        migrations.RemoveField(
            model_name='flag',
            name='is_flag',
        ),
        migrations.AlterIndexTogether(
            name='flag',
            index_together=set([('manual_flag', 'flag'), ('flag', 'manual_flag')]),
        ),
        migrations.AlterIndexTogether(
            name='metric',
            index_together=set([('test_version', 'measurement_start_time')]),
        ),
    ]
