# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20170309_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='input',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
