# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20170412_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedinput',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
