# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_flag_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.Metric'),
        ),
    ]
