# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20170522_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='probe',
            name='country',
            field=models.ForeignKey(blank=True, default=231, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.Country'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='isp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.ISP'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='region',
            field=models.ForeignKey(blank=True, default=3479, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.State'),
        ),
    ]
