# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20170328_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
