# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20170313_1924'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='flag',
            index_together=set([('manual_flag', 'flag'), ('flag', 'manual_flag')]),
        ),
    ]
