# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20170417_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='plugin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='suggested_events',
            field=models.ManyToManyField(blank=True, related_name='suggested_flags', to='event.Event'),
        ),
    ]
