# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20161110_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='region',
            field=models.CharField(default='CCS', max_length=100),
        ),
    ]
