# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20170309_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='test_name',
            field=models.CharField(max_length=50),
        ),
    ]
