# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20170701_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='measurement',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
