# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20170313_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='measurement_start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='test_version',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
