# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20170309_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='options',
            field=models.TextField(null=True),
        ),
    ]
