# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_auto_20170425_1915'),
        ('measurement', '0004_auto_20170424_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutedInput',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='isp',
        ),
        migrations.AlterField(
            model_name='dns',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ISP', verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ISP'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='event.Plan'),
        ),
        migrations.DeleteModel(
            name='ISP',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
