# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_auto_20161116_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutedInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('type_med', models.CharField(choices=[('MED', 'Medicion'), ('DNS', 'Medicion DNS'), ('TCP', 'Medicion TCP'), ('HTTP', 'Medicion HTTP')], default='MED', max_length=50, verbose_name='Tipo de Medicion')),
            ],
        ),
    ]
