# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_auto_20170309_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='test_helpers',
            field=models.TextField(null=True),
        ),
    ]
