# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_auto_20170313_1932'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='metric',
            index_together=set([('test_version', 'measurement_start_time')]),
        ),
    ]
