# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20161129_1949'),
        ('measurement', '0006_auto_20161129_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='suggested_events',
            field=models.ManyToManyField(related_name='suggested_events', to='event.Event'),
        ),
    ]
