# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_auto_20170313_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='test_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
