# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_auto_20170313_2115'),
        ('measurement', '0006_auto_20170309_2308'),
    ]

    operations = [
    ]
