# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_merge_20170320_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flag',
            field=models.CharField(choices=[('hard', 'Hard'), ('muted', 'Muted'), ('none', 'None'), ('soft', 'Soft')], db_index=True, default='none', max_length=10),
        ),
    ]
