# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_auto_20161129_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isp', models.CharField(max_length=100)),
                ('upload', models.CharField(max_length=30, verbose_name='Velocidad de Carga publicitado')),
                ('download', models.CharField(max_length=30, verbose_name='Velocidad de Descarga publicitado')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('amazonas', 'Amazonas'), ('anzoategui', 'Anzoategui'), ('apure', 'Apure'), ('aragua', 'Aragua'), ('barinas', 'Barinas'), ('bolivar', 'Bolivar'), ('carabobo', 'Carabobo'), ('cojedes', 'Cojedes'), ('delta_amacuro', 'Delta Amacuro'), ('distrito_capital', 'Distrito Capital'), ('falcon', 'Falcon'), ('guarico', 'Guarico'), ('lara', 'Lara'), ('merida', 'Merida'), ('miranda', 'Miranda'), ('monagas', 'Monagas'), ('nueva_esparta', 'Nueva Esparta'), ('portuguesa', 'Portuguesa'), ('sucre', 'Sucre'), ('tachira', 'Tachira'), ('trujillo', 'Trujillo'), ('vargas', 'Vargas'), ('yaracuy', 'Yaracuy'), ('zulia', 'Zulia')], default='distrito_capital', max_length=50)),
                ('country', models.CharField(choices=[('venezuela', 'Venezuela')], default='venezuela', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('isp', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='measurement.Plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='flag',
            name='region',
        ),
        migrations.AddField(
            model_name='flag',
            name='probe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='measurement.Probe'),
            preserve_default=False,
        ),
    ]
