# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_mutedinput'),
        ('measurement', '0009_auto_20161130_1823'),
    ]

    operations = [
    ]
