# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_auto_20170327_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='is_flag',
        ),
    ]
