# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_country_state'),
        ('measurement', '0010_merge_20161201_1511'),
    ]

    operations = [
    ]
