# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_remove_flag_is_flag'),
        ('measurement', '0009_auto_20170328_1738'),
    ]

    operations = [
    ]
