# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_merge_20161201_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='probe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='measurement.Probe'),
        ),
        migrations.AlterField(
            model_name='mutedinput',
            name='url',
            field=models.URLField(),
        ),
    ]
