# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 18:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_auto_20161202_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='test_keys',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
