# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_auto_20161202_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='country',
            field=models.ForeignKey(default=231, on_delete=django.db.models.deletion.CASCADE, to='measurement.Country'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='region',
            field=models.ForeignKey(default=3479, on_delete=django.db.models.deletion.CASCADE, to='measurement.State'),
        ),
    ]
