# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0016_auto_20161206_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False)),
                ('type_med', models.CharField(default='medicion', max_length=25, verbose_name='Tipo de Medicion')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='measurement.Metric')),
            ],
            options={
                'db_table': 'flag',
            },
        ),
    ]
