# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0018_auto_20170113_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
