# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0017_auto_20170111_1626'),
        ('measurement', '0019_auto_20170116_1437'),
    ]

    operations = [
    ]
