# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0020_merge_20170117_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricflag',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='measurement.Metric'),
        ),
    ]
