# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0021_auto_20170117_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricflag',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
