# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0023_auto_20170124_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='identification',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
